apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file selenium-grid.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chrome
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file selenium-grid.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
        - env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          image: selenium/node-chrome:4.1.0-20211123
          name: chrome
          resources: {}
      restartPolicy: Always
status: {}
