apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file selenium-grid.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: edge
  name: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: edge
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file selenium-grid.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: edge
    spec:
      containers:
        - env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_GRID_URL
              value: http://localhost:4444
          image: selenium/node-edge:4.1.0-20211123
          name: edge
          resources: {}
      restartPolicy: Always
status: {}
