apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file selenium-grid.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium-hub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file selenium-grid.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: selenium-hub
    spec:
      containers:
        - image: selenium/hub:4.1.0-20211123
          name: selenium-hub
          ports:
            - containerPort: 4442
            - containerPort: 4443
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
