apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file selenium-grid.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  ports:
    - name: "4442"
      port: 4442
      targetPort: 4442
    - name: "4443"
      port: 4443
      targetPort: 4443
    - name: "4444"
      port: 4444
      targetPort: 4444
  selector:
    io.kompose.service: selenium-hub
status:
  loadBalancer: {}
